language: objective-c
osx_image: xcode11.1
podfile: Podfile
before_install:
    - gem install fastlane
    - gem install cocoapods # Since Travis is not always on latest version
    - gem install xcodeproj
    - pod setup
    - pod install --repo-update
script:
    - instruments -s device
    - fastlane tests_ios10
