language: objective-c
osx_image: xcode9.2
script:
    ./xcodebuild.sh
    # xcodebuild test -workspace APNAssistant.xcworkspace -scheme APNAssistant -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5s' -destination 'platform=iOS Simulator,name=iPhone 6 Plus' -destination 'platform=iOS Simulator,name=iPhone 7' -destination 'platform=iOS Simulator,name=iPhone X'
